version: "3.8"

services:
  frontend:
    build:
      context: .
      dockerfile: docker/frontend.Dockerfile
    ports:
      - "80:80"  # Порт для публічного доступу до сайту
    networks:
      - app-network
    restart: always
    depends_on:
      - backend

  backend:
    build:
      context: .
      dockerfile: docker/backend.Dockerfile
    env_file:
      - .env
    networks:
      - app-network
    restart: always
    depends_on:
      - db
      - redis

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    networks:
      - app-network
    restart: always

  redis:
    image: redis:alpine
    networks:
      - app-network
    restart: always

  celery:
    build:
      context: .
      dockerfile: docker/backend.Dockerfile
    command: celery -A tasks worker --loglevel=info
    depends_on:
      - backend
      - redis
    networks:
      - app-network
    env_file:
      - .env
    restart: always

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
