version: '3.9'
services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: kli
      POSTGRES_PASSWORD: kli
      POSTGRES_DB: kli
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    command: redis-server --save 60 1 --loglevel warning
    ports:
      - "6379:6379"

  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    environment:
      APP_ENV: production
      SERVER_PORT: "8080"
      PUBLIC_URL: http://localhost:8080
      DATABASE_URL: postgres://kli:kli@db:5432/kli?sslmode=disable
      REDIS_URL: redis://redis:6379
      JWT_SECRET: supersecretjwtkey
      CLEANUP_INTERVAL: 1h
      FILE_RETENTION: 168h
      STRIPE_CURRENCY: eur
    env_file:
      - backend/.env.example
    depends_on:
      - db
      - redis
    ports:
      - "8080:8080"
    restart: unless-stopped

volumes:
  pgdata:
